Repository invoke-ai/InvokeAI, pull requests merged in 2022-12, with the labels that each got.

#1765 fix(srcinstall): shell installer - `cp` scripts instead of linking
  source_installer/install.sh.in
Labels: bug, install

#1766 Account for flat models
  ldm/invoke/model_cache.py
Labels: bug

#1809 Add windows to test workflows
  .github/workflows/test-invoke-conda.yml
  .github/workflows/test-invoke-pip.yml
  environments-and-requirements/requirements-base.txt
  environments-and-requirements/requirements-win-colab-cuda.txt
Labels: enhancement, CI-CD

#1950 Make Dockerfile cloud ready (tested on runpod)
  .github/workflows/build-container.yml
  docker-build/Dockerfile
  docker-build/run.sh
  ldm/invoke/CLI.py
Labels: CI-CD, docker

#1975 add concurrency to test actions
  .github/workflows/test-invoke-conda.yml
  .github/workflows/test-invoke-pip.yml
Labels: CI-CD

#1971 re-enable wheel install in `test-invoke-pip.yml`
  .github/workflows/test-invoke-pip.yml
Labels: CI-CD

#1332 build: GitHub Action to lint python files with pyflakes
  .github/workflows/pyflakes.yml
Labels: CI-CD

#1970 update (docker-)build scripts, `.dockerignore` and add patchmatch
  .dockerignore
  .github/workflows/build-cloud-img.yml
  docker-build/Dockerfile
  docker-build/build.sh
  docker-build/env.sh
  docker-build/run.sh
  docs/installation/040_INSTALL_DOCKER.md
Labels: docker

#2065 set workflow PR triggers to filter PR-types
  .github/workflows/test-invoke-conda.yml
  .github/workflows/test-invoke-pip.yml
Labels: CI-CD

#2036 optimize `Dockerfile`
  docker-build/Dockerfile
  docker-build/env.sh
Labels: docker

#2110 [docker] use `uname -m` instead of `arch`
  docker-build/env.sh
Labels: docker
