Repository invoke-ai/InvokeAI, pull requests merged in 2023-01, with the labels that each got.

#2111 Fix patchmatch-docs
  docs/CHANGELOG.md
  docs/installation/060_INSTALL_PATCHMATCH.md
  docs/installation/INSTALL_MANUAL.md
Labels: documentation

#2251 update python requirements
  environments-and-requirements/requirements-lin-amd.txt
  environments-and-requirements/requirements-lin-arm64.txt
  environments-and-requirements/requirements-lin-cuda.txt
  environments-and-requirements/requirements-mac-mps-cpu.txt
  environments-and-requirements/requirements-win-colab-cuda.txt
Labels: requirements

#2420 dev: update to diffusers 0.12, transformers 4.26
  environments-and-requirements/requirements-base.txt
Labels: requirements

#2440 fix dimension errors when inpainting model is used with hires-fix
  ldm/invoke/generator/txt2img2img.py
Labels: bug

#2447 fix(inpainting model): blank areas to be repainted in the masked image
  ldm/invoke/generator/diffusers_pipeline.py
Labels: bug
