Repository invoke-ai/InvokeAI, pull requests merged in 2023-04, with the labels that each got.

#3117 fix build-container.yml
  .github/workflows/build-container.yml
Labels: CI-CD, docker

#3128 fix(nodes): use correct torch device in NoiseInvocation
  invokeai/app/invocations/latent.py
Labels: nodes

#3126 feat(nodes): add list_images endpoint
  invokeai/app/api/models/images.py
  invokeai/app/api/routers/images.py
  invokeai/app/cli/commands.py
  invokeai/app/invocations/cv.py
  invokeai/app/invocations/generate.py
  invokeai/app/invocations/image.py
  invokeai/app/invocations/reconstruct.py
  invokeai/app/invocations/upscale.py
  invokeai/app/models/__init__.py
  invokeai/app/models/exceptions.py
  invokeai/app/models/image.py
  invokeai/app/models/metadata.py
  invokeai/app/services/image_storage.py
  invokeai/app/services/processor.py
  invokeai/app/util/__init__.py
  invokeai/app/util/step_callback.py
Labels: api, nodes

#3108 feat(nodes): mark ImageField properties required, add invocation README
  docs/contributing/INVOCATIONS.md
  invokeai/app/services/graph.py
Labels: api, nodes
