Repository invoke-ai/InvokeAI, pull requests merged in 2023-02, with the labels that each got.

#2445 fix broken Dockerfile
  .dockerignore
  .github/workflows/build-container.yml
  docker-build/Dockerfile
  docker-build/build.sh
  docker-build/env.sh
  docker-build/run.sh
  ldm/invoke/CLI.py
Labels: docker

#2458 fix img2img on mps by working around pytorch bug
  ldm/invoke/generator/diffusers_pipeline.py
Labels: bug, macOS

#2457 Prevent actions from running on draft PRs
  .github/workflows/build-cloud-img.yml
  .github/workflows/build-container.yml
  .github/workflows/lint-frontend.yml
  .github/workflows/mkdocs-material.yml
  .github/workflows/pyflakes.yml
Labels: CI-CD

#2450 add workflow to clean caches after PR gets closed
  .github/workflows/clean-caches.yml
Labels: CI-CD

#2472 fix(img2img): do not attempt to do a zero-step img2img when strength is low
  ldm/invoke/generator/diffusers_pipeline.py
Labels: bug

#2442 remove requirements step from install manual
  docs/installation/020_INSTALL_MANUAL.md
Labels: documentation

#2478 Adapt latest changes to Dockerfile
  .dockerignore
  .github/CODEOWNERS
  .github/workflows/build-cloud-img.yml
  .github/workflows/build-container.yml
  docker-build/Dockerfile.cloud
  docker-build/Makefile
  docker-build/env.sh
  docker/Dockerfile
  docker/build.sh
  docker/env.sh
  docker/run.sh
  ldm/invoke/CLI.py
Labels: CI-CD, docker

#2516 Add workflow for PyPI Release
  .github/workflows/pypi-release.yml
  scripts/pypi_helper.py
Labels: CI-CD

#2517 Issue/2487/address docker issues
  .dockerignore
  .github/workflows/build-container.yml
  docker/Dockerfile
  docker/build.sh
  docker/env.sh
  docs/installation/040_INSTALL_DOCKER.md
Labels: docker

#2537 hotfix `build-container.yml`
  .github/workflows/build-container.yml
Labels: CI-CD

#2533 update `pypi_helper.py`
  scripts/pypi_helper.py
Labels: CI-CD

#2524 Update `test-invoke-pip.yml`
  .github/workflows/test-invoke-pip.yml
  ldm/invoke/model_manager.py
Labels: CI-CD

#2532 force torch reinstall
  installer/installer.py
Labels: install

#2530 add platform-specific help instructions to installer
  installer/messages.py
Labels: install

#2597 Huge Docker Update - better caching, don't use root user, include dockerhub and more....
  .dockerignore
  .github/workflows/build-container.yml
  docker/Dockerfile
  docker/build.sh
  docker/env.sh
  docker/run.sh
Labels: CI-CD, docker

#2590 add `merge_group` trigger to test-invoke-pip.yml
  .github/workflows/test-invoke-pip.yml
Labels: CI-CD

#2688 skip huge workflows if not needed
  .github/workflows/build-container.yml
  .github/workflows/test-invoke-pip-skip.yml
  .github/workflows/test-invoke-pip.yml
  README.md
Labels: CI-CD

#2699 [WebUI] Model Merging
  invokeai/backend/invoke_ai_web_server.py
  invokeai/frontend/dist/assets/index-7062a172.js
  invokeai/frontend/dist/assets/index-9237ac63.js
  invokeai/frontend/dist/index.html
  invokeai/frontend/dist/locales/common/en-US.json
  invokeai/frontend/dist/locales/common/en.json
  invokeai/frontend/dist/locales/modelmanager/en-US.json
  invokeai/frontend/dist/locales/modelmanager/en.json
  invokeai/frontend/dist/locales/parameters/en-US.json
  invokeai/frontend/public/locales/common/en-US.json
  invokeai/frontend/public/locales/common/en.json
  invokeai/frontend/public/locales/modelmanager/en-US.json
  invokeai/frontend/public/locales/modelmanager/en.json
  invokeai/frontend/public/locales/parameters/en-US.json
  invokeai/frontend/src/app/invokeai.d.ts
  invokeai/frontend/src/app/socketio/actions.ts
  invokeai/frontend/src/app/socketio/emitters.ts
  invokeai/frontend/src/app/socketio/listeners.ts
  invokeai/frontend/src/app/socketio/middleware.ts
  invokeai/frontend/src/features/system/components/ModelManager/AddModel.tsx
  invokeai/frontend/src/features/system/components/ModelManager/MergeModels.tsx
  invokeai/frontend/src/features/system/components/ModelManager/ModelList.tsx
  invokeai/frontend/src/features/system/store/systemSelectors.ts
  invokeai/frontend/src/features/system/store/systemSlice.ts
  invokeai/frontend/stats.html
Labels: web ui

#2701 fix(xformers): shush about not having Triton available.
  ldm/invoke/__init__.py
Labels: windows

#2700 fix(diffusers_pipeline): ensure `cuda.get_mem_info` always gets a specific device index.
  ldm/generate.py
  ldm/invoke/config/invokeai_configure.py
  ldm/invoke/devices.py
  ldm/invoke/generator/diffusers_pipeline.py
  ldm/invoke/model_manager.py
Labels: bug

#2815 Split requirements / pyproject installation in Dockerfile
  .dockerignore
  .github/workflows/build-container.yml
  docker/Dockerfile
  docker/build.sh
  docker/env.sh
  docker/run.sh
Labels: docker

#2808 add a workflow to close stale issues
  .github/workflows/close-inactive-issues.yml
Labels: CI-CD
